#!/usr/bin/env python3
"""
Robot Volley — full modular part roster (flat-vector comical direction, rich finish).

Generates every part variant as a separate transparent sprite on the locked
skeleton, then builds:
  * _catalog.png    — every part cutout, labeled, grouped by slot
  * _showcase.png   — several mix-and-match robots proving any combo connects

Parts connect because placement is anchored at fixed JOINT LINES (head bottom =
neck, arm/leg tops = shoulder/hip sockets), so differently-sized variants still
meet at the same seams.

    python3 tools/robot/gen_roster.py            # missing only
    python3 tools/robot/gen_roster.py --force
    python3 tools/robot/gen_roster.py --only head-drill torso-light
"""
import argparse
import io
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.join(HERE, "..")
sys.path.insert(0, TOOLS)
import gen_nanobanana as nb  # noqa: E402

ANCHOR = os.path.join(HERE, "refs", "style-anchor", "flatvector-comical-anchor.png")
OUT_DIR = os.path.join(HERE, "refs", "parts-flatvector")

STYLE = (
    "FLAT VECTOR game-art style with a rich polished finish, comical cute mascot "
    "robot. Bold clean geometric shapes, crisp edges, limited palette, smooth soft "
    "single-step shading for gentle form, thin gold accent linework, bright neon rim "
    "on the lit edges. Crimson-red armor (#ff5a5f) with darker red underframe and cool "
    "metallic joints. Premium toy-collectible look — NO photographic texture, NO ink "
    "comic outlines, NO scene, NO cast shadow on the ground. "
    "OUTPUT: the single part only, centered with generous margin, front view, on a "
    "COMPLETELY FLAT UNIFORM MAGENTA (#FF00FF) background for chroma keying — magenta "
    "ONLY behind the part, never inside it. No text, no other parts, no character."
)

# slot, variant, aspect, subject
PARTS = [
    # ---- HEADS (standard already generated by gen_parts.py) ----
    ("head", "magnet", "1:1",
     "the robot's HEAD shaped like a big friendly cartoon horseshoe U-MAGNET, the two "
     "prongs pointing UP with polished silver pole-tips, thin gold accent linework on "
     "the prongs — but the rounded base of the U is a proper ROBOT FACE, with a wide "
     "glowing cyan horizontal visor-eye sitting across the curve of the base like a "
     "friendly smile. IMPORTANT: the two prong tips are completely separate and "
     "independent — there is NO arc, NO bridge, NO beam, NO spark, and NOTHING "
     "connecting or spanning between the two tips; the gap between them is empty and "
     "open. A short rounded neck collar stem at the bottom center so it plugs onto the "
     "body, flat bottom neck edge. The magnet fills the frame."),
    ("head", "drill", "1:1",
     "the robot's HEAD shaped like a big friendly cartoon CONE DRILL-BIT. A wide "
     "crimson armored housing ring at the bottom, and above it a bold tapering metal "
     "CONE with two chunky spiral SCREW FLUTES winding up it to a sharp point. A wide "
     "glowing cyan horizontal visor-eye set across the front of the housing ring at "
     "the bottom, like a friendly face. IMPORTANT: the ENTIRE head IS the drill — this "
     "is NOT a normal robot head with a drill attached. The drill stands straight UP "
     "and DOWN, perfectly vertical and symmetric: the sharp pointed TIP is at the very "
     "TOP pointing UP at the sky, and the BASE is at the BOTTOM. At the bottom center "
     "there is a short rounded NECK COLLAR stem so it plugs onto the body — the "
     "collar's bottom is a flat horizontal neck edge. ORANGE (#fb923c) neon rim glow "
     "and hazard accents. The drill fills the frame."),
    # ---- TORSOS (standard already generated) ----
    ("torso", "heavy", "1:1",
     "the robot's CHEST/TORSO only: a bulkier heavily-armored barrel torso with riveted "
     "bolt studs and three horizontal reinforcement bands, a glowing vertical cyan energy "
     "core, chunky shoulder sockets at the upper sides and hip sockets at the bottom. No "
     "head/arms/legs, flat top and bottom edges."),
    ("torso", "light", "1:1",
     "the robot's CHEST/TORSO only: a LIGHTWEIGHT open exoskeleton TRUSS torso — a "
     "see-through triangulated frame of thin metal girders with an X cross-brace and a "
     "glowing cyan core node in the center, small shoulder + hip sockets. Skeletal and "
     "airy, not a solid plate. No head/arms/legs, flat top and bottom edges."),
    ("torso", "lowCoG", "1:1",
     "the robot's CHEST/TORSO only: a rounded barrel torso with a glowing vertical cyan "
     "core and, set into the LOWER belly, a visible exposed mechanical metal COG/GEAR "
     "wheel, shoulder + hip sockets. No head/arms/legs, flat top and bottom edges."),
    # ---- LEGS (normal already generated by gen_parts.py) ----
    # Socket budget in-game: ~17px wide, sole-anchored, only ~17px peek below the
    # torso — so each variant must read as a bold silhouette (foot / spring / rocket).
    ("leg", "power", "2:3",
     "a single POWER SPRING-LEG only (right side). The ENTIRE leg IS ONLY a thick "
     "coiled metal SPRING standing vertically — fat silver coils, nothing else. "
     "IMPORTANT: NO foot, NO pad, NO sole, NO sneaker, NO boot, NO disc base, NO "
     "armored thigh, NO end-cap housing at the bottom. The spring coils themselves "
     "are the whole silhouette from top to bottom: small silver ball-joint hip nub "
     "at the very top, then continuous spring coils all the way down, ending on the "
     "last coil (that last coil IS the ground contact). Compact, chunky, front view. "
     "Just the one spring."),
    ("leg", "rocket", "1:1",
     "a single SHORT stubby ROCKET-THRUSTER LEG only (right side). The ENTIRE part IS "
     "a compact cartoon rocket thruster standing in place of a foot — SHORT and WIDE "
     "(about as tall as it is wide, NOT a tall thin rocket ship). Bright CRIMSON-RED "
     "(#ff5a5f) bulbous rocket body, small side fins, orange nozzle pointing DOWN with "
     "a tiny idle blue-orange flame at the bottom tip. Small silver ball-joint hip nub "
     "sitting on the very top of the rocket. IMPORTANT: there is NO sneaker, NO boot, "
     "NO separate thigh/shin armor — the short rocket itself is the whole leg. Must "
     "read clearly as a rocket at a glance. Front view. Just the one rocket-leg."),
    # ---- WEAPONS (held props near the front hand) ----
    ("weapon", "axe", "1:1",
     "a small cartoon hand-AXE / hatchet game-item PROP only: short brown handle and a "
     "chunky silver metal blade with a subtle cyan edge glint, diagonal. Just the axe."),
    ("weapon", "ninjaStar", "1:1",
     "a single silver metal NINJA THROWING STAR (shuriken) game-item PROP only: four "
     "sharp points, a small center hole, subtle cyan edge glint. Just the star."),
    ("weapon", "portalGun", "1:1",
     "a small cartoon PORTAL GUN / sci-fi ray-gun game-item PROP only: short chunky "
     "silver-grey body, dark grip, muzzle capped by a glowing RED oval portal disc "
     "(vertical ellipse), subtle cyan edge glint on the metal. Just the gun."),
]

# ---- Skeleton: fixed joint lines so any variant connects at the same seams ----
CANVAS = (760, 940)
BGCOL = (10, 14, 26, 255)
LAYOUT = {
    # slot: (cx, edge_y, max_w, max_h, anchor)
    "head":  (380, 372, 384, 404, "bottom"),
    "torso": (380, 540, 414, 360, "center"),
    "armL":  (250, 452, 120, 236, "top"),
    "armR":  (510, 452, 120, 236, "top"),
    "legL":  (314, 626, 142, 226, "top"),
    "legR":  (446, 626, 142, 226, "top"),
    "weapon": (528, 688, 98, 98, "center"),
}
Z_ORDER = ["legL", "legR", "armL", "armR", "torso", "head", "weapon"]

# Per-variant nudges to close gaps for oddly-proportioned parts (dx, dy, scale).
# Applied on top of the slot's base LAYOUT so odd shapes still meet their seam.
OVERRIDE = {
    # dx is negative because these sheets composite the art UNMIRRORED, and the
    # torso's neck socket is painted left of centre. The game mirrors the art
    # for right-facing robots and flips this nudge with it (src/ui/spriteRobot.js).
    ("head", "magnet"): (-46, 26, 0.7),  # smaller smile-face horseshoe; seat it into the torso
    ("head", "drill"): (-46, 26, 0.85),  # tall vertical cone; scale to match the other heads
    ("leg", "rocket"): (0, 0, 1.0),      # compact rocket thruster; default seat
    ("torso", "light"): (0, 6, 1.04),
}


def cut_part(data):
    im = nb.remove_chroma_bg(Image.open(io.BytesIO(data)))
    return nb.autocrop_alpha(im, pad=2)


def place(im, cfg, ov=None):
    cx, edge_y, mw, mh, anchor = cfg
    if ov:
        dx, dy, sc = ov
        cx, edge_y, mw, mh = cx + dx, edge_y + dy, mw * sc, mh * sc
    scale = min(mw / im.width, mh / im.height)
    w, h = round(im.width * scale), round(im.height * scale)
    r = im.resize((w, h), Image.LANCZOS)
    x = cx - w // 2
    if anchor == "top":
        y = edge_y
    elif anchor == "bottom":
        y = edge_y - h
    else:
        y = edge_y - h // 2
    return r, (x, y)


def load_catalog():
    """catalog[slot][variant] = RGBA image, from files in OUT_DIR."""
    cat = {}
    for fn in os.listdir(OUT_DIR):
        if not fn.endswith(".png") or fn.startswith("_"):
            continue
        slot, variant = fn[:-4].split("-", 1)
        cat.setdefault(slot, {})[variant] = Image.open(os.path.join(OUT_DIR, fn)).convert("RGBA")
    return cat


def assemble(cat, head="standard", torso="standard", leg="normal", weapon=None):
    canvas = Image.new("RGBA", CANVAS, BGCOL)
    arm = cat["arm"]["hand"]
    imgs = {
        "legL": cat["leg"][leg].transpose(Image.FLIP_LEFT_RIGHT),
        "legR": cat["leg"][leg],
        "armL": arm.transpose(Image.FLIP_LEFT_RIGHT),
        "armR": arm,
        "torso": cat["torso"][torso],
        "head": cat["head"][head],
    }
    if weapon:
        imgs["weapon"] = cat["weapon"][weapon]
    # which variant fills each socket, for override lookup
    variant_of = {
        "legL": ("leg", leg), "legR": ("leg", leg),
        "armL": ("arm", "hand"), "armR": ("arm", "hand"),
        "torso": ("torso", torso), "head": ("head", head),
        "weapon": ("weapon", weapon),
    }
    for slot in Z_ORDER:
        if slot not in imgs:
            continue
        fitted, pos = place(imgs[slot], LAYOUT[slot], OVERRIDE.get(variant_of[slot]))
        canvas.alpha_composite(fitted, pos)
    return canvas


def font(size, bold=True):
    name = "Arial Bold.ttf" if bold else "Arial.ttf"
    try:
        return ImageFont.truetype(f"/System/Library/Fonts/Supplemental/{name}", size)
    except Exception:
        return ImageFont.load_default()


def catalog_sheet(cat, out_path):
    rows = [
        ("HEADS", "head", ["standard", "magnet", "drill"]),
        ("TORSOS", "torso", ["standard", "heavy", "light", "lowCoG"]),
        ("LEGS", "leg", ["normal", "power", "rocket"]),
        ("ARM", "arm", ["hand"]),
        ("WEAPONS", "weapon", ["axe", "ninjaStar", "portalGun"]),
    ]
    cell, pad, rowlabel = 240, 18, 30
    cols = 5
    W = pad + cols * (cell + pad)
    H = pad + len(rows) * (rowlabel + cell + pad)
    sheet = Image.new("RGBA", (W, H), BGCOL)
    draw = ImageDraw.Draw(sheet)
    y = pad
    for label, slot, variants in rows:
        draw.text((pad, y), label, font=font(20), fill=(120, 200, 255, 255))
        y += rowlabel
        for i, v in enumerate(variants):
            if slot not in cat or v not in cat[slot]:
                continue
            x = pad + i * (cell + pad)
            im = cat[slot][v].copy()
            im.thumbnail((cell, cell), Image.LANCZOS)
            sheet.alpha_composite(im, (x + (cell - im.width) // 2, y + (cell - im.height) // 2))
            draw.text((x + 4, y + cell - 20), v, font=font(15, False), fill=(230, 235, 255, 255))
        y += cell + pad
    sheet.convert("RGB").save(out_path)
    return out_path


def showcase_sheet(cat, out_path):
    combos = [
        ("standard/standard/normal", dict(head="standard", torso="standard", leg="normal")),
        ("magnet / light / rocket", dict(head="magnet", torso="light", leg="rocket")),
        ("magnet / heavy / power", dict(head="magnet", torso="heavy", leg="power")),
        ("drill / lowCoG + axe", dict(head="drill", torso="lowCoG", leg="normal", weapon="axe")),
        ("drill / std / rocket + star",
         dict(head="drill", torso="standard", leg="rocket", weapon="ninjaStar")),
    ]
    cw, ch = 300, 372
    pad, label_h = 18, 34
    W = pad + len(combos) * (cw + pad)
    H = pad + label_h + ch + pad
    sheet = Image.new("RGBA", (W, H), BGCOL)
    draw = ImageDraw.Draw(sheet)
    for i, (title, kw) in enumerate(combos):
        x = pad + i * (cw + pad)
        bot = assemble(cat, **kw)
        bot.thumbnail((cw, ch), Image.LANCZOS)
        sheet.alpha_composite(bot, (x + (cw - bot.width) // 2, pad + label_h))
        draw.text((x + 4, pad + 6), title, font=font(16), fill=(120, 200, 255, 255))
    sheet.convert("RGB").save(out_path)
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--only", nargs="*")
    ap.add_argument("--sheets-only", action="store_true", help="skip gen, just rebuild sheets")
    args = ap.parse_args()

    client = nb.make_client(nb.load_key())
    style_ref = open(ANCHOR, "rb").read()
    only = set(args.only) if args.only else None

    if not args.sheets_only:
        for slot, variant, aspect, subject in PARTS:
            key = f"{slot}-{variant}"
            if only and key not in only and slot not in only:
                continue
            dest = os.path.join(OUT_DIR, f"{key}.png")
            if os.path.exists(dest) and not args.force:
                print(f"  skip {key} (exists)")
                continue
            print(f"• generating {key} …")
            data = nb.gen_image(client, f"{STYLE}\n\nPART: {subject}",
                                aspect=aspect, style_ref_bytes=style_ref)
            cut_part(data).save(dest)
            print(f"  wrote {os.path.relpath(dest, os.path.join(TOOLS, '..'))}")

    cat = load_catalog()
    c = catalog_sheet(cat, os.path.join(OUT_DIR, "_catalog.png"))
    print(f"Catalog: {os.path.relpath(c, os.path.join(TOOLS, '..'))}")
    s = showcase_sheet(cat, os.path.join(OUT_DIR, "_showcase.png"))
    print(f"Showcase: {os.path.relpath(s, os.path.join(TOOLS, '..'))}")
    print("Done.")


if __name__ == "__main__":
    main()
